Repository Meteor-hanaro/Frontend, pull requests merged in 2024-05, with the labels that each got.

#4 feat: user login page 구현
  src/components/user/Login.js
Labels: enhancement

#8 5 feature/user main view
  public/assets/css/style.css
  src/Router.js
  src/components/user/Main.js
  src/components/user/sidebar/Header.js
  src/pages/MainPage.js
  src/pages/user/LoginPage.js
  src/pages/user/MainPage.js
Labels: feat

#12 feat: video connection, live data transaction
  src/Router.js
  src/WebRTC.js
  src/components/sidebar/Sidebar.js
  src/pages/MainPage.js
  src/pages/VideoPage.js
  src/signaling-server.js
Labels: feat

#14 feat: video page UI
  package.json
  public/assets/css/video.css
  public/index.html
  src/Router.js
  src/WebRTC.js
  src/components/Main.js
  src/pages/video/ProgressBarPage.js
  src/pages/video/RebalancingPage.js
  src/pages/video/VideoPage.js
  src/signaling-server.js
Labels: feat

#17 feat: UI for each screen
  public/assets/css/video.css
  public/assets/img/contract.jpg
  src/Router.js
  src/WebRTC.js
  src/index.js
  src/pages/video/ContractPage.js
  src/pages/video/IdVerificationPage.js
  src/pages/video/ProgressBarPage.js
  src/pages/video/RebalancingPage.js
  src/pages/video/SharingPage.js
  src/pages/video/VideoPage.js
  src/pages/video/WebRTC.js
  src/pages/video/WebRTCContext.js
  src/pages/video/signaling-server.js
Labels: feat

#24 feature/suggestion_model_view_link
  src/Router.js
  src/components/common/NameContainer.js
  src/components/common/SuggestionList.js
  src/components/common/chart/TrafficChart.js
  src/pages/video/IdVerificationPage.js
  src/pages/video/RebalancingPage.js
  src/pages/video/SharingPage.js
  src/pages/video/WebRTC.js
Labels: feat

#25 style: edit file path
  package.json
Labels: style

#22 feat: 간편인증 구현 및 useScript 구현
  src/Router.js
  src/pages/AuthPage.js
  src/useScript.js
Labels: feat🚀, 완료😎

#28 13 feature/pb login
  src/Router.js
  src/components/common/Login.js
  src/contexts/LoginContextProvider.js
  src/pages/pb/LoginPage.js
  src/pages/pb/MainPage.js
Labels: feat🚀

#34 feature/pdf-sign
  package-lock.json
  package.json
  public/assets/css/style.css
  src/Router.js
  src/pages/Sign.js
  src/pages/video/IdVerificationPage.js
  src/pages/video/SharingPage.js
  src/pages/video/SignPage.js
  src/pages/video/WebRTC.js
Labels: feat🚀, 완료😎
