Repository Meteor-hanaro/Frontend, pull requests merged in 2024-06, with the labels that each got.

#39 feature/pb-main-view
  src/auth.js
  src/components/common/Header.js
  src/components/common/Login.js
  src/components/pb/Main.js
  src/contexts/LoginContextProvider.js
Labels: feat🚀, 완료😎

#42 style/change-units-from-px-to-rem
  public/assets/css/video.css
Labels: 완료😎, style

#38 feature/videopage_webrtcconnection_improve
  package.json
  public/assets/css/video.css
  src/Router.js
  src/SetupProxy.js
  src/components/common/NameContainer.js
  src/components/common/SuggestionList.js
  src/components/user/Main.js
  src/config/signaling-server.js
  src/contexts/WebRTCContext.js
  src/index.js
  src/pages/AuthPage.js
  src/pages/Sign.js
  src/pages/consult/ContractPage.js
  src/pages/consult/IdVerificationPage.js
  src/pages/consult/RebalancingPage.js
  src/pages/consult/SignPage.js
  src/pages/etc/FormPage.js
  src/pages/etc/MainPage.js
  src/pages/etc/VideoPage.js
  src/pages/video/ProgressBarPage.js
  src/pages/video/SharingPage.js
  src/pages/video/WebRTC.js
  src/pages/video/signaling-server.js
Labels: feat🚀, 완료😎

#46 feature/vip-login
  src/Router.js
  src/pages/user/LoginPage.js
  src/pages/user/MainPage.js
Labels: feat🚀, 완료😎

#37 feature/consentView
  public/assets/css/style.css
  src/components/common/FundCheckItem.js
  src/pages/consult/ContractPage.js
  src/pages/video/ConsentPage.js
  src/pages/video/SharingPage.js
Labels: feat🚀, 완료😎

#47 feature/enter-to-video-page
  package-lock.json
  package.json
  public/assets/css/style.css
  src/Router.js
  src/components/user/Main.js
Labels: feat🚀, 완료😎

#48 fix/conflit_solve
  src/pages/video/SharingPage.js
Labels: 완료😎, fix

#49 fix/conflict_solve2
  src/pages/video/SharingPage.js
Labels: 완료😎, fix

#52 feature/vip-main-view
  src/components/user/Main.js
Labels: feat🚀, 완료😎

#56 feature/customer-portfolio-management
  public/assets/css/style.css
  src/Router.js
  src/components/pb/Sidebar.js
  src/components/pb/fund/fundDetail.js
  src/components/pb/fund/fundList.js
  src/components/pb/portfolio/portfolioGraph.js
  src/components/pb/portfolio/portfolioTable.js
  src/components/sidebar/Sidebar.js
  src/pages/pb/FundPage.js
  src/pages/pb/PortfolioPage.js
Labels: feat🚀

#55 feature/real-user's-consulting-room
  public/assets/css/style.css
  src/Router.js
  src/components/user/Main.js
  src/contexts/LoginContextProvider.js
Labels: feat🚀, 완료😎

#58 feature/vip-main-view
  public/assets/css/style.css
  src/components/pb/Main.js
  src/components/pb/Sidebar.js
  src/components/pb/fund/fundDetail.js
  src/components/sidebar/Sidebar.js
  src/components/user/ConsultCard.js
  src/components/user/Main.js
  src/components/user/ProfileCard.js
  src/components/user/ProfileDetail.js
  src/pages/pb/FundPage.js
Labels: feat🚀, 완료😎

#61 fix/refactoring_code_after_conflict_resolve_0603
  public/assets/css/style.css
Labels: 작업중🤮, fix

#64 feature/customer-portfolio-management
  public/assets/css/style.css
  src/Router.js
  src/components/pb/Main.js
  src/components/pb/portfolio/portfolioTable.js
Labels: feat🚀, fix

#67 feature/consentView
  public/assets/css/style.css
  public/assets/css/video.css
  src/components/common/FundCheckItem.js
  src/components/common/FundContract.js
  src/pages/video/ConsentPage.js
  src/pages/video/WebRTC.js
Labels: feat🚀, 완료😎

#63 feature/suggestion_accept_deny_view
  public/assets/css/style.css
  public/assets/css/video.css
  src/components/common/SuggestionList.js
  src/components/common/chart/TrafficChart.js
  src/pages/consult/RebalancingPage.js
  src/pages/video/ConsentPage.js
  src/pages/video/SharingPage.js
Labels: feat🚀, 완료😎

#69 feature/pb-main-portfolio-connection
  public/assets/css/style.css
  src/components/pb/Main.js
  src/components/pb/fund/fundDetail.js
  src/components/pb/portfolio/portfolioGraph.js
  src/components/pb/portfolio/portfolioTable.js
  src/pages/pb/PortfolioPage.js
Labels: 작업중🤮, feat🚀

#72 feature/users-logout
  public/assets/css/style.css
  src/components/Main.js
  src/components/common/Header.js
  src/components/common/Login.js
  src/contexts/LoginContextProvider.js
  src/pages/pb/LoginPage.js
  src/pages/pb/MainPage.js
  src/pages/user/LoginPage.js
  src/pages/user/MainPage.js
Labels: feat🚀, 완료😎

#73 feature/display vip portfolio suggestion list
  src/Router.js
  src/components/pb/Main.js
  src/components/pb/suggestion/SuggestionCard.js
  src/components/pb/suggestion/SuggestionList.js
  src/components/user/Main.js
  src/pages/consult/RebalancingPage.js
  src/pages/pb/SuggestionPage.js
Labels: feat🚀, 완료😎

#77 feature/consentPageAPIConnection
  src/pages/consult/ConsentPage.js
  src/pages/video/SharingPage.js
Labels: feat🚀, 완료😎

#79 feature/decorate-auth
  public/assets/css/style.css
  public/assets/css/video.css
  src/pages/AuthPage.js
  src/pages/consult/AuthPage.js
  src/pages/consult/IdVerificationPage.js
  src/pages/consult/Sign.js
  src/pages/consult/SignPage.js
  src/pages/etc/useScript.js
  src/pages/video/SharingPage.js
Labels: feat🚀, 완료😎

#57 feature/webrtc_https
  .gitignore
  package.json
  src/SetupProxy.js
  src/components/Card.js
  src/components/Main.js
  src/components/common/SuggestionList.js
  src/components/common/chart/EChart.js
  src/components/common/chart/ReportChart.js
  src/components/pb/fund/fundDetail.js
  src/config/signaling-server.js
  src/contexts/WebRTCContext.js
  src/index.js
  src/pages/BankerPage.js
  src/pages/ProfilePage.js
  src/pages/consult/IdVerificationPage.js
  src/pages/consult/Sign.js
  src/pages/etc/FormPage.js
  src/pages/etc/MainPage.js
  src/pages/etc/VideoPage.js
  src/pages/etc/useScript.js
  src/pages/video/ProgressBarPage.js
  src/pages/video/VideoPage.js
Labels: 작업중🤮, feat🚀

#71 feature/decorate-portfolio-graph
  src/components/pb/Sidebar.js
  src/components/pb/portfolio/portfolioGraph.js
  src/components/pb/portfolio/portfolioTable.js
Labels: 완료😎, style

#82 feature/users-state-check
  src/components/pb/Main.js
Labels: feat🚀, 완료😎

#87 fix/setenvbeserveruri_webrtcroomurl_intro
  src/Router.js
  src/SetupProxy.js
  src/components/common/Header.js
  src/components/common/Login.js
  src/components/etc/Card.js
  src/components/etc/Main.js
  src/components/pb/Main.js
  src/components/pb/fund/fundDetail.js
  src/components/pb/fund/fundList.js
  src/components/pb/portfolio/portfolioGraph.js
  src/components/pb/portfolio/portfolioTable.js
  src/components/pb/suggestion/SuggestionList.js
  src/components/user/Main.js
  src/pages/consult/ConsentPage.js
  src/pages/consult/IdVerificationPage.js
  src/pages/consult/RebalancingPage.js
  src/pages/video/PrivateRoute.js
Labels: 완료😎, fix

#88 feature/login-logout-detail
  src/components/common/Header.js
  src/components/common/Login.js
  src/contexts/LoginContextProvider.js
  src/pages/pb/LoginPage.js
  src/pages/pb/PortfolioPage.js
  src/pages/user/LoginPage.js
Labels: feat🚀, 완료😎

#91 feature/vip-search
  public/assets/css/style.css
  src/components/pb/Main.js
Labels: feat🚀, 완료😎

#95 feature/consult-request-pb2vip
  public/assets/css/style.css
  src/components/pb/Main.js
  src/components/user/Main.js
  src/config/signaling-server.js
Labels: feat🚀, 완료😎

#99 feat/root-landing-page
  public/assets/css/style.css
  public/assets/img/pb.png
  public/assets/img/vip.png
  src/Router.js
  src/components/RootCard.js
  src/pages/RootPage.js
Labels: feat🚀, 완료😎

#102 fix/consult-request-pb2vip
  src/components/pb/Main.js
  src/components/user/Main.js
  src/pages/video/PrivateRoute.js
  src/pages/video/VideoPage.js
Labels: feat🚀, 완료😎

#106 fix/apply-jwt-token
  src/auth.js
  src/components/pb/portfolio/portfolioTable.js
  src/pages/video/PrivateRoute.js
Labels: feat🚀, 완료😎

#110 feature/consult-ending-page
  package-lock.json
  package.json
  public/assets/img/meteor.png
  src/Router.js
  src/components/pb/ConsultRegister.js
  src/components/pb/Main.js
  src/components/user/ConsultEndCard.js
  src/pages/pb/ConsultEndingPage.js
  src/pages/user/ConsultEndingPage.js
Labels: feat🚀, 완료😎

#109 feature/system_admin_page_advanced
  public/assets/css/style.css
  public/assets/img/consultdetail.png
  src/Router.js
  src/components/common/Header.js
  src/components/common/SuggestionList.js
  src/components/etc/Card.js
  src/components/etc/Main.js
  src/components/pb/Main.js
  src/components/system_admin/AdminCard.js
  src/components/system_admin/Header.js
  src/components/system_admin/Main.js
  src/components/system_admin/VipRegister.js
  src/components/user/ConsultCard.js
  src/components/user/ConsultDetail.js
  src/components/user/Main.js
  src/pages/system_admin/AdminPage.js
  src/pages/system_admin/AdminPrivateRoute.js
  src/pages/user/ConsultDetailPage.js
  src/pages/video/PrivateRoute.js
  src/pages/video/ProgressBarPage.js
  src/pages/video/SharingPage.js
  src/pages/video/VideoPage.js
Labels: 작업중🤮, feat🚀

#93 feature/one-to-one-in-consulting-room
  src/components/pb/Main.js
  src/config/signaling-server.js
  src/contexts/WebRTCContext.js
  src/pages/etc/VideoPage.js
  src/pages/video/PrivateRoute.js
  src/pages/video/VideoPage.js
Labels: feat🚀, 완료😎

#113 fix/edit_indexjs_privateroute
  src/index.js
  src/pages/video/PrivateRoute.js
Labels: 완료😎, fix

#114 feature/append-suggestion
  public/assets/css/style.css
  src/Router.js
  src/components/pb/suggestion/SuggestionAdd.js
  src/components/pb/suggestion/SuggestionCard.js
  src/components/pb/suggestion/SuggestionList.js
  src/pages/pb/SuggestionAddPage.js
  src/pages/pb/SuggestionPage.js
Labels: feat🚀, 완료😎

#118 feature/real-time linkage to consultation page
  package-lock.json
  package.json
  src/pages/consult/ConsentPage.js
  src/pages/consult/RebalancingPage.js
  src/pages/video/SharingPage.js
Labels: feat🚀, 완료😎

#111 feature/connect websocket
  public/assets/css/style.css
  public/assets/css/video.css
  src/components/user/Main.js
  src/pages/consult/AuthPage.js
  src/pages/consult/IdVerificationPage.js
  src/pages/consult/RebalancingPage.js
  src/pages/consult/Sign.js
  src/pages/video/ProgressBarPage.js
  src/pages/video/SharingPage.js
Labels: 작업중🤮, feat🚀, fix

#119 fix/webrtcroom_limitconnection
  src/components/pb/Main.js
  src/components/user/Main.js
  src/config/signaling-server.js
  src/contexts/WebRTCContext.js
  src/index.js
  src/pages/video/PrivateRoute.js
Labels: 완료😎, fix

#120 feature/handle-consult-ending
  src/Router.js
  src/components/consult/Header.js
  src/components/pb/ConsultRegister.js
  src/components/user/ConsultCard.js
  src/components/user/ConsultDetail.js
  src/components/user/ConsultEndCard.js
  src/components/user/Main.js
  src/pages/video/VideoPage.js
Labels: feat🚀, 완료😎

#121 feature/append suggestion
  public/assets/css/style.css
  src/Router.js
  src/components/pb/fund/fundDetailForAddition.js
  src/components/pb/portfolio/portfolioTable.js
  src/components/pb/suggestion/SuggestionAdd.js
  src/components/pb/suggestion/SuggestionCard.js
  src/components/pb/suggestion/SuggestionList.js
  src/pages/consult/RebalancingPage.js
  src/pages/pb/FundAddPage.js
  src/pages/video/PrivateRoute.js
Labels: feat🚀, 완료😎

#122 fix: webrtc limitconnection advanced
  src/config/signaling-server.js
  src/contexts/WebRTCContext.js
  src/pages/video/PrivateRoute.js
  src/pages/video/SharingPage.js
  src/pages/video/VideoPage.js
Labels: 완료😎, fix

#123 fix/rebalancingpage
  src/contexts/WebRTCContext.js
  src/pages/consult/RebalancingPage.js
Labels: 완료😎, fix

#125 feature/connection websocket datas
  public/assets/css/style.css
  src/components/common/AuthModal.js
  src/pages/consult/AuthPage.js
  src/pages/consult/ConsentPage.js
  src/pages/consult/IdVerificationPage.js
  src/pages/consult/RebalancingPage.js
  src/pages/consult/Sign.js
  src/pages/video/SharingPage.js
Labels: feat🚀, 완료😎, fix
